# -*- coding: utf-8 -*-
"""run_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OuOvxDnG4208VKL98_8XUXpYfa2f4C1b
"""

import os

# Run Arapersonality Dataset
print('The results for Arapersonality Dataset')
print('------------------------------')
os.system("python /content/project/project/Models/Araper.py")
##########################################################

# Run Fused Arabic Personality (rapersonality + MSAPersonality) Dataset
print('The results for Fused Arabic Personality Dataset')
print('------------------------------')
# os.system("python /content/project/project/Models/run_model_combine.py")
##########################################################

# Run MSAPersonality Dataset
print('The results for MSAPersonality Dataset')
print('------------------------------')
# os.system("python /content/project/project/Models/run_model_msapersonality1.py")
##########################################################

# Run Essays Dataset
print('The results for Essays Dataset')
print('------------------------------')
# os.system("python /content/project/project/Models/run_model_essays.py")
##########################################################

